# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: qTox Blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  qTox â€“ easy to use, secure, distributed, instant messaging, audio and video
  calling software based on Tox technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://qtox.github.io" # the base hostname & protocol for your site
#twitter_username: qTox
github_username:  qTox

# Build settings
markdown: kramdown
